name: Plugin Build

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '8'
          cache: maven

      - uses: SpraxDev/Action-SpigotMC@v5
        with:
          versions: 1.8.8
          generateSrc: false
          generateDoc: false

      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
          cache: maven

      - name: Maven build
        run: |
          java -version
          mvn clean install

      - name: Create result directory
        run: mkdir result

      - name: Copy SurvivalGames Plugin
        run: cp $(find target/SurvivalGamesPlugin-*.jar) result/SurvivalGamesPlugin.jar

      - uses: actions/upload-artifact@v4
        with:
          name: compiled-plugins
          path: result
          retention-days: 7